name: Acceptance Tests
on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    paths-ignore:
      - 'README.md'
  schedule:
    - cron: '0 13 * * *'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: '1.15'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.3.4

    - name: Get dependencies
      run: |
        go mod download

    - name: Build
      run: |
        go build -v .

  test:
    name: Matrix Test
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        version:
          - 3.3.12
        terraform:
          - '0.12.29'
          - '0.13.5'
          - '0.14.11'
          - '0.15.5'
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: '1.15'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.3.4

    # TODO: convert this to `services`
    - name: Start Rundeck
      run: |
        ./rundeck.sh start ${{ matrix.version }}

    - name: Get dependencies
      run: |
        go mod download
        
    - name: TF acceptance tests
      timeout-minutes: 10
      env:
        TF_ACC: "1"
        TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform }}

        RUNDECK_URL: http://localhost:4440
        RUNDECK_AUTH_TOKEN: 1d08bf61-f962-467f-8ba3-ab8a463b3467
      run: |
        go test -v -cover -count 1 ./rundeck/
